### ISSUE TITLE
希望可以像xx-net一样把系统托盘加上！

### ISSUE THREAD

**Issue by fletchere** [xyuanmu/XX-Mini#11]
RT。

**Comment by yeahwu** [comment]
直接点击goagent-gtk.py，会有惊喜的

**Comment by xyuanmu** [comment]
@yeahwu 原来 goagent-gtk 还有这功能，我一直傻傻的 python proxy.py

**Comment by PvCDp** [comment]
@yeahwu 刚下载，好像没有goagent-gtk.py这个文件？不过你的版本比xxnet扫描ip快，就是不清楚网速是否给力，总体来说非常不错，希望一直更新下去。thanx

**Comment by fletchere** [comment]
谢谢@yeahwu，解决了，不过不知道是不是封的厉害还是怎么的，网络不太给力。

**Comment by fletchere** [comment]
把原来xx-net的goodip.txt复制过去后，速度也上来了。
