### ISSUE TITLE
升级了下Python版本为2.7.13

### ISSUE THREAD

**Issue by xyuanmu** [xyuanmu/XX-Mini#122]
更新Windows系统的 python 版本为2.7.13，下载cp2713那个，供尝鲜 ^_^
Linux系统就不要升级2.7.13版本了，有unicode的bug，估计今年的2.7.14版本会解决。

下载地址：
[https://git.io/XX-Mini](https://git.io/XX-Mini)

**Comment by jzp820927** [comment]
是个大半年后的更新，值得拥有。

**Comment by yeahwu** [comment]
@xyuanmu 兄，好久不见。为啥不升级一下xx-net的python呢？

**Comment by xyuanmu** [comment]
@yeahwu 已经弄好了，等会儿提交pull。

**Comment by 5sq** [comment]
谢谢更新！
