### ISSUE TITLE
建议添加从github导入google ip的功能

### ISSUE THREAD

**Issue by Z-Y00** [xyuanmu/XX-Mini#124]
希望可以从github上一些维护的google hosts简单导入到我本地的配置之中，不用自己来扫描ip。
（或许应该给上游提issue，不过上游似乎太忙了）
（自己手工来搞，还有host格式问题）

**Comment by jzp820927** [comment]
都很少更新，估计不太现实

**Comment by Z-Y00** [comment]
例如这个，两天前才更新的
https://github.com/racaljk/hosts

也可以直接把我们扫描出来的 good_ip.txt 定期上传github，然后pr

**Comment by jzp820927** [comment]
其实如果有点基础，你可以直接写个脚本，来实现 IP 同步。

**Comment by GoogleGFW** [comment]
IP不是通用的哦

**Comment by Z-Y00** [comment]
@GoogleGFW 
不是很懂，喵喵喵？

**Comment by xyuanmu** [comment]
@GoogleGFW 说的没错，IP不通用的，XX需要的IP是GGC，而hosts中的IP不全是GGC IP。

**Comment by Z-Y00** [comment]
THX～
 got it
