### ISSUE TITLE
xxnet部署问题

### ISSUE THREAD

**Issue by candy2107** [xyuanmu/XX-Mini#125]
您好!
有好几个人反馈xxnet升级python 2.7.13 即3.3.2 版本后部署服务端时无法弹出窗口 , 能否修复该问题?

**Comment by jzp820927** [comment]
慢慢等吧，现在处理问题的频率比较低，估计哪天空了，看到了，就处理了。

**Comment by xyuanmu** [comment]
谢谢关注，已经修复，待合并pull :smile:

**Comment by candy2107** [comment]
十分感謝!
