### ISSUE TITLE
MERCURY MW4530R v1 OpenWrt运行XX-Mini失败，求助！

### ISSUE THREAD

**Issue by erdcy** [xyuanmu/XX-Mini#136]
### 固件版本：
OpenWrt Chaos Calmer 15.05.1 / LuCI 15.05-149-g0d8bbd2 Release (git-15.363.78009-956be55) 

### python版本及安装情况：
Package name | Version
python | 2.7.9-6
python-base | 2.7.9-6
python-codecs | 2.7.9-6
python-compiler | 2.7.9-6
python-ctypes | 2.7.9-6
python-db | 2.7.9-6
python-decimal | 2.7.9-6
python-distutils | 2.7.9-6
python-email | 2.7.9-6
python-gdbm | 2.7.9-6
python-light | 2.7.9-6
python-logging | 2.7.9-6
python-multiprocessing | 2.7.9-6
python-ncurses | 2.7.9-6
python-openssl | 2.7.9-6
python-pydoc | 2.7.9-6
python-sqlite3 | 2.7.9-6
python-unittest | 2.7.9-6
python-xml | 2.7.9-6

ps. 在路由器software里install python，就装了这一大堆，但是安装源里没有wiki里提到的pyopenssl

### 遇到的问题
Putty以root账户登陆后，用`python /xxx/proxy.py`运行，提示：
Traceback (most recent call last):
  File "proxy.py", line 26, in <module>
    from config import config
  File "/etc/XX-Mini/lib/config.py", line 10, in <module>
    from OpenSSL import version as openssl_version
ImportError: No module named OpenSSL

是不是因为没有pyopenssl呢？

**Comment by xyuanmu** [comment]
可以看一下这个：https://github.com/xyuanmu/XX-Mini/wiki/OpenWrt-%E4%B8%8B%E9%85%8D%E7%BD%AE-XX-Mini

**Comment by erdcy** [comment]
卡在pyopenssl上了，找了半天没找到。

**Comment by erdcy** [comment]
在14.07版本的openwrt库里，找到一个pyopensll，直接安装
`opkg install http://openwrt.proxy.ustclug.org/barrier_breaker/14.07/ar71xx/generic/packages/oldpackages/pyopenssl_0.10-1_ar71xx.ipk --force-depends --force-overwrite`
再运行python /XX-Mini/proxy.py，开始扫描ip了。

**Comment by erdcy** [comment]
xx-net有web-ui，如何查看xx-mini在路由器上的运行状态呢？
