### ISSUE TITLE
MW4530R路由器，OpenWrt，通过username，password打开代理鉴定遇到的问题总结

### ISSUE THREAD

**Issue by erdcy** [xyuanmu/XX-Mini#137]
## 运行条件
MW4530R路由器，14.07版OpenWrt，XX-Mini 1.3.1
##安装方法
1，在openwrt.org网站下载14.07版固件刷入；
2，安装python、python-openssl以及python-pyopenssl；
3，拷贝XX-Mini目录下的proxy.ini文件到在XX-Mini/data目录，重命名为manual.ini，修改[listen]和[pac]下的ip地址为0.0.0.0，其余部分根据需要修改；
4，在路由器/etc目录下新建rc.local文件，文件内容为
```
python /XX-Mini所在目录/XX-Mini/proxy.py
exit 0
```
5，上传XX-Mini到路由器自选目录；
6，重启路由器，XX-Mini即自动运行。
7，下载XX-Mini/data目录下的CA文件，导入到PC浏览器，手机等终端。
## 不打开代理用户鉴定功能运行情况
python占用内存30%左右，两天运行正常。
## 使用中遇到的问题
1，打开代理用户鉴定功能后，XX-Mini会挂掉，路由器仍然在工作，但无法通过XX-Mini代理上网。XX-Mini的pac功能失效，如果设置了pac，终端无法上baidu等内网，也无法fq上外网。python进程占用内存50%或以上，无法kill python进程，用reboot命令无法重启路由器，必须拔掉电源。
2，iPhone浏览器打开youtube，可以刷新页面但非常卡，查看python进程，cpu占用有时高达100%，内存占用60%以上，点击播放一直处于缓冲状态；
3，youtube客户端无法浏览，打开后显示“加载时出错，请点按以重试”。

## 另外附上在群晖DSM系统（基于Linux，硬件远强于MW4530R路由器）打开代理用户鉴定的使用情况和问题
1，python占用系统内存50M左右，百分比约3~5%，运行两天没有挂掉；
2，iPhone浏览器第一次fq会提示输入用户名和密码，以后不再提示；
3，部分需要fq的客户端每次打开会提示输入用户名和密码，输入或者忽略都能fq上网；
4，iPhone浏览器可以播放youtube，youtube app可以浏览但无法播放（群晖DSM上运行XX-Net代理时，youtube app可以播放）。

@xyuanmu

**Comment by erdcy** [comment]
@xyuanmu 打开代理鉴定后24小时内，xx-mini死了3次。运行环境时openwrt15.05.1，python-openssl是直接安装的，pyopenssl是在14.07的old packages里找的。

**Comment by erdcy** [comment]
@jzp820927 在以前的issues里看到你也使用了代理鉴定功能，有没有遇到上述问题啊？谢谢！

**Comment by xyuanmu** [comment]
卡死是完全没反应还是上不了网？可以适当减少扫描IP线程数。
第2个问题，关闭验证后iPhone能正常连上吗？
证书错误应该是导入的证书问题，这个跟验证应该没关系，删掉pc-2证书重新导入看问题会不会复现，另：火狐的证书和IE不通用的。

**Comment by erdcy** [comment]
@xyuanmu 
## 路由器的现象：
XX-Mini死掉的时候，路由器还在工作，通过pac方式任何网站都不能访问，直连代理也不能上网，所以判断XX-Mini死掉了。在路由器openwrt的webUI看不到python的process（正常时可以看到python的process，cpu占用一般不大，内存占用最大时会到60%左右），在路由器的webUI执行重启，也不能恢复启动XX-Mini，只有拔掉路由器电源才能恢复启动XX-Mini（部署的时候，把XX-Mini加入了rc.local文件以实现系统启动时，启动XX-Mini）。今天上午9点过关掉了代理鉴定功能，到目前XX-Mini还在正常工作，怀疑死掉与代理鉴定功能有关。

## 1楼PC上的问题：
XX-Mini关闭代理鉴定功能，iPhone是一直可以上网的。

**Comment by xyuanmu** [comment]
在电脑上IE证书同名是能导入多个，火狐不行，手机就不清楚了。XX-Net的证书名与XX-Mini不同可以同时导入。
至于验证我是一直都开着的，不过是在电脑里，路由器没有试过，所以也不知道问题出在哪，为了不影响使用就暂时关闭验证吧，抱歉！

**Comment by SeaHOH** [comment]
可以把 openwrt 上生成的 CA 拿去替换其它所有地方的 CA，确保统一。

**Comment by erdcy** [comment]
从我使用的情况看，iPhone上同名证书只能导入一次。
pc上使用没有问题，路由器上暂时关闭验证。
谢谢！

Sent from my mobile.
Best regards, Yanjun Li

在 2017年8月31日，下午5:32，xyuanmu <notifications@github.com<mailto:notifications@github.com>> 写道：


在电脑上IE证书同名是能导入多个，火狐不行，手机就不清楚了。XX-Net的证书名与XX-Mini不同可以同时导入。
至于验证我是一直都开着的，不过是在电脑里，路由器没有试过，所以也不知道问题出在哪，为了不影响使用就暂时关闭验证吧，抱歉！

**Comment by erdcy** [comment]
@SeaHOH 把openwrt生成的CA，拷贝到pc上的XX-Mini目录，替换原来的CA即可？

**Comment by jzp820927** [comment]
@erdcy 鉴定没遇到过什么问题，应该是个例吧。

**Comment by erdcy** [comment]
@jzp820927 在pc上开鉴定也正常，就是在openwrt上开鉴定，XX-Mini死掉了。

**Comment by SeaHOH** [comment]
@erdcy 是的，这样就统一了，不再存在同名而内容不同。

**Comment by erdcy** [comment]
@SeaHOH 多谢！明天到单位试试

**Comment by SeaHOH** [comment]
不客气。不过这只是解决了证书问题，不知道对验证功能是否有影响。

**Comment by jzp820927** [comment]
那就不清楚了，我是在 PC 上用的，ow 上没用过

**Comment by erdcy** [comment]
@SeaHOH @jzp820927 多谢二位，有空把路由器恢复出场设置，只装一个XX-Mini再试试。

**Comment by erdcy** [comment]
@SeaHOH 试了把路由器上CA拷贝到PC替换原来的CA，然后在pc上的firefox重新导入新的CA，上google等提示错误。这个方法看来行不通

**Comment by SeaHOH** [comment]
PC 上的 mini 重启没有？
火狐要先删除再重启导入。

**Comment by erdcy** [comment]
@SeaHOH 先停了mini，然后替换了CA，然后启动mini。firefox上的是先删除再导入的，不知道问题出在哪里。

**Comment by SeaHOH** [comment]
火狐删除后要重启

**Comment by erdcy** [comment]
下周上班再试试，多谢！

Sent from my mobile.
Best regards, Yanjun Li

在 2017年9月1日，下午5:19，SeaHOH <notifications@github.com<mailto:notifications@github.com>> 写道：


火狐删除后要重启
