### ISSUE TITLE
新扫出的慢ip替换旧的快ip问题

### ISSUE THREAD

**Issue by sishentibu** [xyuanmu/XX-Mini#14]
![2016-03-17_210620](https://cloud.githubusercontent.com/assets/13832182/13846761/6e0fab1a-ec84-11e5-90e4-e2b08a4ab985.png)
如图，慢的ip把快的ip替换了，是程序问题，还是我哪里设置问题？

我就换了自己的id，然后改了下data文件夹下的good_ip.txt  ，新建了ip_range.txt

**Comment by jzp820927** [comment]
如果新建了 ip_range.txt，则只会扫描 ip_range.txt 里面的 IP 段，你被替换的 IP 段，是不是不再 ip_range.txt 里面？

**Comment by xyuanmu** [comment]
判断慢的IP还有一个指标就是连接出错的次数*1000，因为该IP连接出错过所以被K了，如果IP数没有达到设置的最大值（默认3000）也是不会被移除的。

**Comment by sishentibu** [comment]
@jzp820927 应该不会，应该我都是往里面添加ip段，然后用cheekiptool导出ip段。自己没有手动去重、精简过

**Comment by sishentibu** [comment]
@xyuanmu 了解了。只要不是出问题那我就放心了
