### ISSUE TITLE
提问，为什么Mini能扫除两三百的ip，但是连YouTube却很慢？

### ISSUE THREAD

**Issue by OuyangIPC** [xyuanmu/XX-Mini#141]
很容易出现连接超时的现象，我用XX-net的时候只有一个ip也能正常看YouTube的视频，只是视频清晰度不够高，并没有出现连接超时的问题。我想说的是，net和Mini的核心都是一样的，为什么结果却有些差别呢？各位使用者你们也是一样吗？

**Comment by OuyangIPC** [comment]
配一张图
![youtube](https://user-images.githubusercontent.com/21274341/30769417-5acfda90-a04a-11e7-8553-c17a23e38df9.jpg)

**Comment by xyuanmu** [comment]
最近封锁比较严重，可以用 [checkiptools](https://github.com/xyuanmu/checkiptools) 扫描一遍IP库筛选一下IP段

**Comment by OuyangIPC** [comment]
@xyuanmu 好的，谢谢解答

**Comment by Piglet1994** [comment]
为什么你的还可以用  我现在打开都是warning

**Comment by OuyangIPC** [comment]
@Piglet1994 最近能扫出较多IP了呀，今天公司的台式机上设置的线程数是5，XX-net能扫出3000个IP，虽然检查IP之后只有1200多能用，不过比以前的三四百好多了；昨晚才看了我的Mini，能扫出1000多点IP了，不过好像还是比较慢，出现“连接超时”的情况少了写了

**Comment by xyuanmu** [comment]
这里有一份我挑选的IP段，可以替换看看：[ip_range.txt](https://gist.githubusercontent.com/xyuanmu/80cbe8bbb9f926f10889/raw/7aa5ec7107e5eb76aeda0b2df1e1e4debb00764b/ip_range_good.txt)

**Comment by OuyangIPC** [comment]
@xyuanmu 好的，回去试试，感谢

**Comment by rickertanks** [comment]
何必XX-NET一棵树吊死，用得那么蛋疼！换个方法享受丝滑般流畅！给大家推荐更好的方法，点我头像查看吧！享受丝滑流畅！
