### ISSUE TITLE
Windows Defender 报毒?

### ISSUE THREAD

**Issue by lndnxp** [xyuanmu/XX-Mini#143]
还是我中奖了?

![capture04](https://user-images.githubusercontent.com/32247328/31055714-c0523c9a-a6f9-11e7-8d8b-dda61057b72c.PNG)
![capture00](https://user-images.githubusercontent.com/32247328/31055719-c61a42a8-a6f9-11e7-9875-57f9cc6e6fa7.PNG)
![capture01](https://user-images.githubusercontent.com/32247328/31055731-e9822cec-a6f9-11e7-905f-398177379a0b.PNG)
![capture02](https://user-images.githubusercontent.com/32247328/31055737-ef0ee312-a6f9-11e7-82de-43ffadcc1a31.PNG)

**Comment by lndnxp** [comment]
好像是使用管理员权限启动goagent.exe 会自动导入证书 defender就认为是木马

**Comment by xyuanmu** [comment]
程序本身是没有问题的，添加信任就行了。
goagent.exe 里有 bat2exe 的代码，所以报毒，所有bat转换成exe的执行文件mse都会报毒的。

**Comment by lndnxp** [comment]
@xyuanmu 受教了
