### ISSUE TITLE
xxnet-mini什么时候可以更新

### ISSUE THREAD

**Issue by Payaml** [xyuanmu/XX-Mini#149]
因为X大的原因导致ipv4全部失效，gae的升级导致无法扫描到ipv4的ip，开启了ipv6用了一段时间，但因为不能扫描ip所以很快就不能用了。去xx-net完整版的github看了下，发现已经出了可以同时扫描ipv4和ipv6，虽然还是测试版，但使用上事没有什么问题了，所以想问下mini版什么时候可以更新，个人感觉mini版用起来会更顺手，简便一些

**Comment by jzp820927** [comment]
同感

**Comment by Payaml** [comment]
目前唯一可用的方法就是用checkiptools扫描了ip再导入mini中使用，不过工程量大了很多，用起来也不是很方便，所以还是希望能尽快的跟进xx-net完整版的进度，更新下mini

**Comment by Payaml** [comment]
checkiptools扫描的ipv4 ip可用用两天，不过失效的特别快，感觉基本要转投ipv6了，相对来说要稳定很多

**Comment by jzp820927** [comment]
找几个稳定的 v6 的 IP 放进 mini 应该也没啥问题 v6 又没干扰，一般不会失效

**Comment by wz7465** [comment]
要想用的爽，加前置，网上免费http代理一大把，提供一个速度一般的供测试210.101.131.229：8080
高速的自己找。
