### ISSUE TITLE
ipv6 fail

### ISSUE THREAD

**Issue by halalia** [xyuanmu/XX-Mini#156]
按照md文件中介绍，下载了两个txt文件，在ini中修改了ippool前面的减号、ipv6=1
但是运行开始就warning ipv6 fail。不过同样局域网中别人有使用ipv6的
剩下的全部是warning no enough ip

**Comment by halalia** [comment]
另外还有 ，改回ivp4的话
有warning status 302，并且文件夹中看不到pac文件

**Comment by xyuanmu** [comment]
不支持ipv6的网络需要开启teredo，访问下方的网址看能不能通过：
http://test-ipv6.com/index.html.zh_CN

**Comment by gosmmsw** [comment]
何必XX-NET一棵树上吊死，换个工具，享受丝滑般流畅！ 
推荐一个自用的shadowsocks  SS/SSR服务商，一直在用，速度杠杠的~|价|格|优|惠|低至5元/50G/月。在最近跑路关停潮日益严重的日子,依旧坚挺~已屏蔽国内ip，需翻墙访问～
http://cp.dawangidc.com/aff.php?aff=523
购买服务后请看配置教程
https://fqjsjl.tumblr.com/

**Comment by rsdfdaeew** [comment]
何必XX-NET一棵树吊死，用得那么蛋疼！换个方法享受丝滑般流畅！给大家推荐更好的方法，点我头像查看吧！享受丝滑流畅！

**Comment by yychenhengyu** [comment]
之前已经按照方法开启了teredo隧道，正常使用了很长一段时间，但是最近开始提示我“network IPv6 fail”，然后就死活下载不了gfwlist.txt，用不了，不知道为啥，明明我没动过设置

**Comment by Payaml** [comment]
连不上teredo服务器了而已，换一个稳定的服务器就可以了

**Comment by lon91ong** [comment]
我也遇到了相同的问题，用XX-net可以正常启动ipv6，换mini就不行了，提示warning ipv6 fail
这就能排除teredo服务的问题了

**Comment by Payaml** [comment]
公司的电脑一点问题也没有，家里的应该是网络的问题，被封锁了，提示warning ipv6 fail

**Comment by gjbg1989** [comment]
系统 IPv6 （隧道）正常，貌似 Mini v1.3.3 正常😂
#9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂（非校园）经验（至3.10.4版）

**Comment by gjbg1989** [comment]
😱 #144
