### ISSUE TITLE
登陆Gmail  提示 “出了点问题 抱歉，出了点问题。请重试。”

### ISSUE THREAD

**Issue by rob0ts** [xyuanmu/XX-Mini#157]

**Comment by xyuanmu** [comment]
你GAE服务端上传的版本是多少？

**Comment by rob0ts** [comment]
"server": "goproxy r101 (go1.8.3 (appengine-20170809), linux/amd64)"

**Comment by rob0ts** [comment]
@yeahwu  "server": "goproxy r101 (go1.8.3 (appengine-20170809), linux/amd64)"

**Comment by rob0ts** [comment]
@xyuanmu  "server": "goproxy r101 (go1.8.3 (appengine-20170809), linux/amd64)"

**Comment by xyuanmu** [comment]
goproxy的不兼容
