### ISSUE TITLE
xyuanmu兄，有一个关于自动扫描模块的想法，你给点意见。

### ISSUE THREAD

**Issue by jzp820927** [xyuanmu/XX-Mini#16]
XX-NET 和 XX-MINI 的核心功能就是 IP自动扫描，可以说 IP自动扫描是这2个项目的灵魂，现在 P老大的 goproxy 又开始开发了，而且性能不俗，可以说 性能超过 PYthon 版GAE代理(很多网友经过实测得出的结论)。goproxy 虽然性能相当好，但是却没有最核心的 IP 扫描功能。我在想 xyuanmu兄，能不能把 XX 的IP扫描核心代码提取出来给 goproxy 做一个扫描模块。可以做成独立于 Goproxy 的 PY 脚本，比如，在现在 XX-mini 的基础上，增加一个 autoscangop.py  脚本文件，其实现的功能就是定时从 XX的实时扫描生成的 good_ip.txt 文件中提取前 50 个IP，然后更新到 goproxy 的 gae.json（gae.user.json）配置文件的 google_hk 区段里面，实时更新IP数据，实现和 XX一样的功能。

不晓得 xyuanmu兄 对我的想法，有何意见？

**Comment by xyuanmu** [comment]
我觉得，另外给goproxy用python写扫描IP有点鸡肋，毕竟gop是封装后使用，所以得另外开一个扫描的工具，扫描到IP修改了文件后还得重启gop才能使用，跟自己扫IP就少了修改文件的步骤而已，但是提取xx-net的扫描功能工作量却不小，而且还要集成python。

**Comment by jzp820927** [comment]
那看来还是得手工了，主要现在IP变化太快了，很少有稳定的IP了，手工也挺累的

**Comment by xyuanmu** [comment]
现在IP封锁策略的确比较难搞，我这边goa完全用不了，换IP一连没一分钟就挂，现在测试的时候干脆放几百个IP进去勉强能用，gop稍微好些，但速度上就大打折扣了，自动扫IP是gae类工具未来的趋势。

**Comment by jzp820927** [comment]
之前 IP基本上都是挺稳定了，只要不封锁短期内就不会变化，不过近几天时间，我观察到，IP变动非常频繁，基本上一天要变动2，3次，反正一个24段，总有可用IP，但是一直在不停变化，所以 goa / gop 这种固定域名IP模式，已经很难适用了，只有实时扫描才能应对现在的状况。不知道这个IP变动情况是个别情况，还是都一样。不知道是 google 的策略，还是 GFW 的杰作。

**Comment by jzp820927** [comment]
我想我可能已经知道了为什么扫好的ip.放进去马上就死掉，好像这次防火墙升级主要是对ssl_sock加密算法方法的干扰阻断，换个加密方式就行了.反正我这里换了这个加密方式之后，连接就正常了，再没有出现过马上死掉的现象。把ECDHE-RSA-AES128-SHA方式改成AES128-SHA方式，以goagent-3.23最后哪个版本为例，用notepad++打开proxylib.py文件，找到ciphers='ECDHE-RSA-AES128-SHA'，应该在1771行和1773行，然后改写成ciphers='AES128-SHA'，大家试试看。

@xyuanmu 上面是 @cixi666 的最新发现，你试试看，对你IP失效有没有帮助，说不定可以改进下 XX-mini

**Comment by xyuanmu** [comment]
@jzp820927 不行，换了还是一样挂

**Comment by jzp820927** [comment]
那就没办法了，只能堆IP了，看 goproxy 以后有没有计划做自动扫描了。
