### ISSUE TITLE
ipv6 is ok, 但是connect fail, xxnet可用, 不知何故?

### ISSUE THREAD

**Issue by deathadder2042** [xyuanmu/XX-Mini#164]
![02](https://user-images.githubusercontent.com/32247328/41810581-9ec4e9f0-7733-11e8-94fd-3e42bf984374.PNG)
![00](https://user-images.githubusercontent.com/32247328/41810585-a97581ca-7733-11e8-8418-66cd3519b079.PNG)

**Comment by xiangcoolk** [comment]
@xyuanmu 今天同样发现test-ipv6正常，但用不了。是否跟google更新服务器证书有关？

**Comment by zzd2358** [comment]
https://share.weiyun.com/5KqnYpe    替换cacert.pem删除date目录CA证书重新导入

**Comment by AnyWAT** [comment]
😂(114200)分享资源已经删除
复制3.12.2或更新版XX-Net 内的 code\XXX\gae_proxy\local\cacert.pem 覆盖Mini 的同名文件即可

**Comment by deathadder2042** [comment]
[https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/gae_proxy/local/cacert.pem](https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/gae_proxy/local/cacert.pem)
另存为cacert.pem并替换mini中的cacert.pem
感谢楼上各位帮助^_^
