### ISSUE TITLE
xx-mini v1.2 pac模式有问题

### ISSUE THREAD

**Issue by newcastlecy** [xyuanmu/XX-Mini#18]
[pac]
enable = 1
ip = 0.0.0.0
在局域网并不能被代理

**Comment by xyuanmu** [comment]
加上
[linten]
ip = 0.0.0.0

**Comment by newcastlecy** [comment]
[listen]
ip = 0.0.0.0 这个肯定是加上了，

就是A，打开[pac]  [listen] 0.0.0.0， A的本地ip有多个段192.168.1.X  10.10.10.X 192.168.5.X
B主机用A的指定192.168.1.X段ip 做pac, http://192.168.1.X:8086/proxy.pac 不能访问
而且 A自身在用127.0.0.1:8086/proxy.pac 也不能访问，
XXNET无此问题...

**Comment by xyuanmu** [comment]
启动的时候看看最前面的概要Pac Server后是什么地址
```
Pac Server          : http://192.168.1.108:8086/proxy.pac
```

**Comment by newcastlecy** [comment]
是10段的ip，这个不对，应该要192.168.1.X  这个才行

**Comment by xyuanmu** [comment]
那个10段的IP能共享到局域网吗？

**Comment by newcastlecy** [comment]
测试了1.1和 1.0 也有问题

// Proxy Auto-Config file generated by autoproxy2pac, 2016-03-23 09:41:07
function FindProxyForURL(url, host) {
    var autoproxy = 'PROXY 0.0.0.0:8087';
    var blackhole = 'PROXY 0.0.0.0:8086';
    var defaultproxy = 'DIRECT';

function FindProxyForURLByAutoProxy(url, host) {
    var lastPos;
    do {
        if (autoproxy_host.hasOwnProperty(host)) {
            return 'PROXY 0.0.0.0:8087';
        }
        lastPos = host.indexOf('.') + 1;
        host = host.slice(lastPos);
    } while (lastPos >= 1);
    return 'DIRECT';
}

**Comment by xyuanmu** [comment]
你的pac更新失败了，访问pac链接后加上 ?flush 强制更新：http://127.0.0.1:8086/proxy.pac?flush

**Comment by xyuanmu** [comment]
哦，那是之前犯的一个错误，打开 proxy.py 修改228：
```py
urllib2.urlopen('http://%s:%s/proxy.pac' % (config.PAC_IP, config.PAC_PORT))
# 改成下面的
urllib2.urlopen('http://127.0.0.1:%d/%s' % (config.PAC_PORT, config.PAC_FILE))
```

**Comment by xyuanmu** [comment]
发现问题了，原因是修改 [listen] ip为0.0.0.0之后更新出错1.1和1.2之后的都有这个问题。

**Comment by newcastlecy** [comment]
1.2.1 ，并没有解决问题：
![image](https://cloud.githubusercontent.com/assets/3032427/14008944/c6cafd62-f1c1-11e5-83c6-d32f1cf6c810.png)

不是对应的ip，依然不可访问

**Comment by xyuanmu** [comment]
再刷新一次，pac是昨天的

**Comment by newcastlecy** [comment]
1.2.1 ，并没有解决问题：
ip正常了，但是自动代理只能用于chrome，
![image](https://cloud.githubusercontent.com/assets/3032427/14009573/29053924-f1c8-11e5-906d-a79c5a777124.png)

其他浏览器，IE无效
![image](https://cloud.githubusercontent.com/assets/3032427/14009626/b1442ac0-f1c8-11e5-9769-f5e349c358b2.png)

**Comment by xyuanmu** [comment]
你有试着重启IE吗？IE更新pac后重启才会生效的。

**Comment by newcastlecy** [comment]
重启电脑也试了，mini不行，xx正常

xyuanmu <notifications@github.com>于2016年3月24日星期四 14:12写道：

**Comment by xyuanmu** [comment]
那算了，你还是用net吧

**Comment by newcastlecy** [comment]
😂😂😂😓

xyuanmu <notifications@github.com>于2016年3月24日星期四 14:19写道：

**Comment by xyuanmu** [comment]
我已经查不出哪里还有问题了，pac方面我就动了升级的代码，而且是1.1版本开始，如果连1.0也用不了那真不知道是哪里的问题了。
下面是我在局域网电脑里的测试图：
![ie](https://cloud.githubusercontent.com/assets/12442896/14010135/79e3de9a-f1cd-11e5-820b-63d349c5907e.png)

**Comment by newcastlecy** [comment]
![image](https://cloud.githubusercontent.com/assets/3032427/14010629/cfdfe434-f1d1-11e5-8da1-943b275ddef6.png)


只有一个ip段是正常的，但是 本地ip有多个段192.168.1.X 10.10.10.X 192.168.5.X
就打不开了，不知道xx怎么处理多个ip段的问题

**Comment by newcastlecy** [comment]
1.2.2 本地ip有多个段192.168.1.X 10.10.10.X 192.168.5.X 还是不行，托盘选pac，前面的 勾 没有变化，还在禁用那里

**Comment by xyuanmu** [comment]
你试试这个早期版本：https://mega.nz/#!hUsD3IzB!_SdBiamTTv9n89wAjok6Q4jN7mFFb2-p1u7vd3qrkwA
或者试试管理员身份运行goagent.exe，如果还不能监听多个IP段，那我真的没办法了。托盘那个看看是不是还有其他代理或者被安全软件阻止了。

**Comment by newcastlecy** [comment]
![image](https://cloud.githubusercontent.com/assets/3032427/14058257/e30227ae-f355-11e5-9dca-6c91ed1ebd9c.png)
proxy-python2.7.11 这个版本没问题，oyeah

**Comment by xyuanmu** [comment]
那暂时用着这个版本吧，能否麻烦测试下这个 [1.0.1版本](https://github.com/xyuanmu/XX-Mini/releases/download/1.0/XX-Mini_Win_v1.0.1.zip)，如果不可以监听所有IP段，修改 proxy.ini ，[system] log_file = 1，然后再运行一段时间，将 data\local.log 里的内容发给我看下，谢谢！

**Comment by newcastlecy** [comment]
log：

Mar 26 20:41:47.217 - [DEBUG] network is ok, cost:130 ms
Mar 26 20:41:47.224 - [INFO] SSL use version:TLSv1
Mar 26 20:41:47.580 - [INFO] load ip range file:D:\XX-Mini\ip_range.txt
Mar 26 20:41:47.626 - [INFO] load google ip_list num:3000, gws num:3000
Mar 26 20:41:47.651 - [INFO] load manual.ini success
Mar 26 20:41:47.651 - [DEBUG] ## GAEProxy set keep_running: True
Mar 26 20:41:47.653 - [INFO] ------------------------------------------------------
Mar 26 20:41:47.653 - [INFO] Python Version     : 2.7.11
Mar 26 20:41:47.653 - [INFO] OS                 : Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
Mar 26 20:41:47.655 - [INFO] Listen Address     : 0.0.0.0:8087
Mar 26 20:41:47.655 - [INFO] GAE APPID          : xxxxx
Mar 26 20:41:47.655 - [INFO] Pac Server         : http://0.0.0.0:8086/proxy.pac
Mar 26 20:41:47.656 - [INFO] ------------------------------------------------------
Mar 26 20:42:25.495 - [INFO] scan_ip add ip:202.28.85.166 time:1134
Mar 26 20:42:25.508 - [INFO] remove_slowest_ip:125.235.30.215 handshake_time:547, fails:2
Mar 26 20:43:59.763 - [INFO] scan_ip add ip:216.58.199.162 time:424
Mar 26 20:43:59.774 - [INFO] remove_slowest_ip:183.78.5.168 handshake_time:547, fails:2
......
Mar 26 22:02:26.787 - [INFO] scan_ip add ip:216.58.195.133 time:595
Mar 26 22:02:26.800 - [INFO] remove_slowest_ip:167.206.12.83 handshake_time:541, fails:2
Mar 26 22:02:29.502 - [INFO] PAC from:127.0.0.1:55039 GET /proxy.pac 
Mar 26 22:02:29.715 - [INFO] GAE CONNECT www.google.com.sg:443 
Mar 26 22:02:29.758 - [INFO] ssl error: EOF occurred in violation of protocol (_ssl.c:590), create full domain cert for host:www.google.com.sg

**Comment by xyuanmu** [comment]
看日志并没有太大异常，好像生成证书出错，看了下ssl的代码初步判断是缺少文件，有可能是 calendar.py，你能不能再帮我一个忙，下载这份压缩包 [proxy-debug.zip](https://drive.google.com/file/d/0B4lIa3JGSHbQZ2Zad1RmMk5UN2M/view)，解压后照常运行 goagent.exe，应该可以绑定所有IP段，能正常访问谷歌后双击运行 !) debug_file.bat ，然后将 !) debug_file.txt 里的内容发一下，我看看到底少了哪些文件，拜托了！

**Comment by newcastlecy** [comment]
D:\XX-Mini\proxy_dir.pyo

**Comment by xyuanmu** [comment]
就这个文件？debug能监听所有IP吗？

**Comment by newcastlecy** [comment]
manual.ini 是 0.0.0.0

xyuanmu <notifications@github.com>于2016年3月26日周六 下午11:49写道：

**Comment by xyuanmu** [comment]
我是问，是不是所有的IP段都能监听到 192.168和10.10那个？

**Comment by newcastlecy** [comment]
debug 所有的IP段 正常

**Comment by xyuanmu** [comment]
debug实际用的1.0.1的代码，根据运行后只生成proxy_dir.pyo来看，1.0.1的代码不存在监听所有IP段的问题，你下载 [XX-Mini_win_v1.1.1.zip](https://github.com/xyuanmu/XX-Mini/releases/download/1.1/XX-Mini_win_v1.1.1.zip) 试试看，看能否监听所有IP段，如果不行可能跟升级了OpenSSL库有关。

**Comment by newcastlecy** [comment]
XX-Mini_win_v1.1.1.zip  所有的IP段 已正常 ，感谢
