### ISSUE TITLE
是用火狐google搜索栏出错

### ISSUE THREAD

**Issue by angle1895** [xyuanmu/XX-Mini#19]
用1.2版本搜索时出现错误,当用ga,gp是则是要求输入验证码,火狐版本43,44.

403. That’s an error.

Your client does not have permission to get URL /sorry/IndexRedirect?continue=https://www.google.com/search%3Fq%3D1%26ie%3Dutf-8%26oe%3Dutf-8&q=CGMSBA6SAroYloHJtwUiGQDxp4NLoo6pMbAFv-Wn0EdrxMkcAFYpBY8qM2h0dHBzOi8vd3d3Lmdvb2dsZS5jb20vc2VhcmNoP3E9MSZpZT11dGYtOCZvZT11dGYtOA from this server. That’s all we know.

**Comment by sishentibu** [comment]
是指的在google主页搜索时？
ff42下没有问题

**Comment by angle1895** [comment]
火狐自带的搜索

**Comment by xyuanmu** [comment]
火狐自带的搜索应该会自动跳转才是，43和45两个版本都测试过的。

**Comment by angle1895** [comment]
有时候会出现一段时间,当出现时用全新无任何插件火狐也一样,
