### ISSUE TITLE
必须要赞一下1.2.2版，

### ISSUE THREAD

**Issue by yeahwu** [xyuanmu/XX-Mini#26]
修改证书名，和添加ip信息都是很实用的功能。
感谢xyuanmu的维护，希望后期拿出你的拿手好戏，着重优化一下ip段，让mini飞起！

**Comment by xyuanmu** [comment]
XX-Mini 还是保持大写的IP段比较妥，考虑到不同地区的封锁。
这里介绍一个提取优良IP段的简单方法：
* 自己用 checkgoogleip 或者XX-Net扫描IP
* 将日志（支持XX-Net日志scan_ip以及good_ip）通通复制到 ip_tmpok.txt，用 [checkiptools](https://github.com/xyuanmu/checkiptools) 提取IP段。
这里有一份3W的IP段，是我这边比较优秀的，电信的应该可以用上一段时间：[ip_range_good.txt](https://gist.githubusercontent.com/xyuanmu/80cbe8bbb9f926f10889/raw/ip_range_good.txt)

**Comment by yeahwu** [comment]
给力，就是懒不愿自己弄，呵呵
