### ISSUE TITLE
请加入对OS X的支持

### ISSUE THREAD

**Issue by cpmbwo** [xyuanmu/XX-Mini#27]
只要在50行 if sys.platform.startswith("linux"): 这里加入 or darwin 就可以了。

**Comment by xyuanmu** [comment]
我没有X系统，你试试下载源码，加上看能否正常运行。或者干脆删掉if：
```py
sys.path.append(work_path + '/lib.egg/lib/')

**Comment by cpmbwo** [comment]
现在的代码直接运行会提示导入config模块失败。我是直接把linux替换为darwin后，可以正常运行。我的系统是OS X 10.11.

**Comment by xyuanmu** [comment]
源码指的是 Source code，既然能正常运行那下次发布时Linux和X并在一起。
