### ISSUE TITLE
请教下下载程序问题

### ISSUE THREAD

**Issue by sishentibu** [xyuanmu/XX-Mini#28]
在github下载程序有什么好方法吗？（当然实际上并不仅仅是这个软件）
我在 https://github.com/xyuanmu/XX-Mini/releases 下载win下程序。但是使用浏览器自带下载，基本上都是90%左右就断了。
用fdm也是差不多到95%左右。（手动设置代理也一样）
用迅雷也是经常解压的时候就出错了。。
有啥比较靠谱的下载方法不？　

题外话，新版怎么换成ｘｘ的图标了

**Comment by yeahwu** [comment]
挂代理吧，win下面
linux下很简单
wget -c  https://github.com/xyuanmu/XX-Mini/releases

**Comment by xyuanmu** [comment]
断流可以尝试用xx-net全局代理下载，试过可以下载。之所以换xx的图标因为好看，嗯，就这样。

**Comment by yeahwu** [comment]
啥时候改图标了？俺用的就是最新1.22版，不还是python图标？linux版

**Comment by xyuanmu** [comment]
Linux的图标没改

**Comment by sishentibu** [comment]
@yeahwu 一直开着xx-mini的啊，还是说你指的别的？

**Comment by yeahwu** [comment]
就是叫你全局代理下载，用lantern或者ss

**Comment by sishentibu** [comment]
@xyuanmu 没有安装xx-net。
如果我用火狐，把autoproxy设成全部使用代理是不是一样？
还是说要把ie代理给改了？

**Comment by sishentibu** [comment]
@yeahwu 好吧，竟然还要再用别的软件。。。

**Comment by yeahwu** [comment]
把autoproxy设为全局代理也应该是可以的，因为mini的包算小的，应该没问题。

**Comment by sishentibu** [comment]
@yeahwu Good! 一下就下好了。比我刚才那二三十k的速度好多了
