### ISSUE TITLE
win下火狐仍旧出现google无法搜索的现象

### ISSUE THREAD

**Issue by yeahwu** [xyuanmu/XX-Mini#3]
RT

**Comment by xyuanmu** [comment]
刚才试了下，可以啊，你火狐版本是多少？

**Comment by yeahwu** [comment]
火狐是44版，是这样的，俺用的是超级托拽，选定字段向右拖搜索。结果www.google.com/search跳转不了google.com.hk。试了下xx没有这样的问题，自动跳转。
然后还有一个问题，俺解包python27.zip文件，然后再压缩，启动时出现下面这样的情况。必须用你那个压缩包才行，这是啥子情况？
![233](https://cloud.githubusercontent.com/assets/13328328/13735579/6332a634-e9e6-11e5-9376-dd5c7e2042d1.JPG)

**Comment by xyuanmu** [comment]
你压缩包是不是多加了层目录？

因为是这里都能正常搜索，不知道问题是出在哪里。
![firefox](https://cloud.githubusercontent.com/assets/12442896/13740926/48f6359c-ea0e-11e5-8c5e-9e696e84dfe7.png)
你试试将 proxy_handler 第115行改成：
```
            content_length = 'Content-Length: 0\r\n' if host.endswith('.google.com.hk') or host.endswith('www.google.com.hk') else ''

**Comment by yeahwu** [comment]
@xyuanmu 兄，改鸟后有效，非常棒
是的，压缩的时候多了层目录，感谢

**Comment by xyuanmu** [comment]
有效就行，另外我想问下改成这个会不会也有效，我这边测试是可以的：
```
            content_length = 'Content-Length: 0\r\n' if host.startswith('www.google.com') else ''

**Comment by yeahwu** [comment]
刚试了一下，也有效。

**Comment by xyuanmu** [comment]
嗯，那就用这个了，避免其他谷歌域名失效的问题
