### ISSUE TITLE
linux上关闭log_scan = 0 好像无效哇

### ISSUE THREAD

**Issue by yeahwu** [xyuanmu/XX-Mini#34]
RT

**Comment by jzp820927** [comment]
https://github.com/xyuanmu/XX-Mini/issues/12 已经实机验证，log 开关可用

**Comment by yeahwu** [comment]
哦，俺理解错了，想问一下xyuanmu兄，怎么关闭终端输出ip信息。谢鸟

**Comment by xyuanmu** [comment]
修改 google_ip.py 和 gae_handler.py，删掉 xlog.info('good ip num:%d, bad ip num:%s'... 开头的两行代码即可，一个文件一个。

**Comment by jzp820927** [comment]
直接后台运行，不就什么日志都没了

**Comment by yeahwu** [comment]
@xyuanmu 谢鸟
