### ISSUE TITLE
OS X 下2个问题。

### ISSUE THREAD

**Issue by cpmbwo** [xyuanmu/XX-Mini#37]
1. cert_util.py 第445行 ../../data/gae_proxy/CA.crt。这个路径是错的。如果以proxy.py所在目录为当前目录，那么应该是 ./data/CA.crt 。否则的话，可能需要一个启动脚本。

2. https的网站能打开，非加密的http网站打不开。正常来说在浏览器点击go按钮后，terminal那边会显示GAE开头的一个网址信息，但是现在打开http的网站，terminal那边一点反应都没有。

**Comment by xyuanmu** [comment]
导入证书的路径确实有问题，http的问题，下载1.1.1版本，修改proxy.py，startswith看看是否能正常连接。

**Comment by jzp820927** [comment]
为什么我都没有 http 的问题呢

**Comment by cpmbwo** [comment]
1.1.1版本修改startswith后，一切正常，http和https都能打开。

**Comment by xyuanmu** [comment]
你试试这个，替换 proxy.py 和 lib.egg  [1.2.4-beta.tar.gz](https://github.com/xyuanmu/XX-Mini/files/200741/1.2.4-beta.tar.gz) ，看能否解决http问题

**Comment by cpmbwo** [comment]
出错！

Traceback (most recent call last):
  File "proxy.py", line 62, in <module>
    from config import config
  File "/Users/gkj/Applications/XX-Mini/lib.egg/lib/config.py", line 143, in <module>
  File "/Users/gkj/Applications/XX-Mini/lib.egg/lib/config.py", line 49, in load
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'public_appid' in section: 'gae'

**Comment by xyuanmu** [comment]
用这份proxy.ini替换原来的：[ini.tar.gz](https://github.com/xyuanmu/XX-Mini/files/200752/ini.tar.gz)

**Comment by cpmbwo** [comment]
2个都替换后，都能正常连接了。 偶尔会有些警告。

[WARNING] read request line empty

[WARNING] direct_handler.handler send Transfer-Encoding t:0 e:error(32, 'Broken pipe') www.google.com.hk//_/chrome/newtab?espv=2&ie=UTF-8

[WARNING] APPID error:400 url:http://qsearch.media.net/bql.php?v=1&&hvsid=00001459586766531018068776883276&        （这个很长很长，我只截取了一点点）

**Comment by xyuanmu** [comment]
那个警告不用管，最近IP慌，我这里也经常出现。
对了能帮忙测试下证书的问题吗？到 XX-Mini 目录新建一个 lib 文件夹，用压缩软件打开 lib.egg，提取 cert_util.py 到 lib 文件夹，修改445行，然后删掉 lib.egg 里面原有的 cert_util.py，重启XX-Mini看能否导入成功。

**Comment by cpmbwo** [comment]
这样可否？mv lib.egg lib.zip。然后解压lib.zip

**Comment by xyuanmu** [comment]
可以，不过解压删除后要改回egg

**Comment by cpmbwo** [comment]
这个目录结构对不？
.-(~/XX-Mini)-------------------------------------------------------------(xxx@xxx)-
`--> ls
total 168
drwx------  11 gkj  staff  -       374B Apr  2 16:59 .
drwx------   6 gkj  staff  -       204B Mar 31 18:19 ..
-rwxr-xr-x   1 gkj  staff  -       2.7K Apr  2 14:53 __genpy__.py
-rw-r--r--   1 gkj  staff  -       3.2K Mar 12 15:57 cacert.pem
drwxr-xr-x   8 gkj  staff  -       272B Mar 31 20:32 data
-rw-r--r--   1 gkj  staff  -        42K Mar 31 16:30 ip_range.txt
drwxr-xr-x  23 gkj  staff  -       782B Apr  2 15:33 lib
-rw-------   1 gkj  staff  nodump  8.9K Apr  1 11:19 proxy.ini
-rw-r--r--   1 gkj  staff  -       9.9K Apr  2 15:33 proxy.py
-rw-r--r--   1 gkj  staff  -        73B Mar 12 15:57 proxy_dir.py
-rwxr--r--   1 gkj  staff  -        53B Apr  1 22:08 start.command
.-(~/XX-Mini)-------------------------------------------------------------(xxx@xxx)-
`--> ls lib
total 536
drwxr-xr-x  23 gkj  staff  -  782B Apr  2 15:33 .
drwx------  11 gkj  staff  -  374B Apr  2 16:59 ..
-rwxr-xr-x   1 gkj  staff  -  2.6K Apr  1 11:39 appids_manager.py
-rwxr-xr-x   1 gkj  staff  -   21K Apr  1 11:55 cert_util.py
-rwxr-xr-x   1 gkj  staff  -  5.8K Apr  1 12:27 check_ip.py
-rwxr-xr-x   1 gkj  staff  -  5.7K Mar 14 17:03 check_local_network.py
-rwxr-xr-x   1 gkj  staff  -  6.0K Apr  1 11:47 config.py
-rwxr-xr-x   1 gkj  staff  -  2.9K Mar 14 13:38 connect_control.py
-rwxr-xr-x   1 gkj  staff  -   20K Apr  2 16:08 connect_manager.py
-rwxr-xr-x   1 gkj  staff  -  8.9K Jan 20 10:11 direct_handler.py
-rwxr-xr-x   1 gkj  staff  -   29K Mar 24 19:41 gae_handler.py
-rwxr-xr-x   1 gkj  staff  -   24K Apr  1 12:10 google_ip.py
-rwxr-xr-x   1 gkj  staff  -  4.0K Mar 26 19:53 google_ip_range.py
-rwxr-xr-x   1 gkj  staff  -  3.9K Dec 21 10:09 ip_utils.py
-rwxr-xr-x   1 gkj  staff  -  5.5K Dec 29 12:15 openssl_wrap.py
-rwxr-xr-x   1 gkj  staff  -   18K Apr  2 15:31 pac_server.py
-rwxr-xr-x   1 gkj  staff  -   14K Apr  2 16:02 proxy_handler.py
drwxr-xr-x   8 gkj  staff  -  272B Apr  2 15:33 pyasn1
-rwxr-xr-x   1 gkj  staff  -  1.9K Dec 29 12:15 scan_ip_log.py
-rwxr-xr-x   1 gkj  staff  -  7.0K Mar 24 13:46 simple_http_client.py
-rwxr-xr-x   1 gkj  staff  -   13K Apr  1 08:51 simple_http_server.py
-rwxr-xr-x   1 gkj  staff  -   27K Mar 26 16:45 socks.py
-rwxr-xr-x   1 gkj  staff  -  7.9K Mar 24 13:47 xlog.py
.-(~/XX-Mini)-------------------------------------------------------------(gkj@KG-MBP)-
`-->

start.command是我从xx-net借鉴过来的。这个目录启动xx-mini后是正常的。

**Comment by xyuanmu** [comment]
对的，启动后可以正常导入证书吗？

**Comment by cpmbwo** [comment]
github对换行符解析好有问题。
启动后显示： [INFO] GoAgent CA exist.
我要先把原来的证书删掉吗？

**Comment by xyuanmu** [comment]
是的，删掉会重新生成并导入，之前的会作废，如果导入不成功，会提示ssl问题的

**Comment by cpmbwo** [comment]
cert_util.py 第445行 ../../data/gae_proxy/CA.crt  改为  ./data/CA.crt 后是可以正常导入的。无论当前目录是否是proxy.py所在的目录。

**Comment by xyuanmu** [comment]
好的，谢谢你！

**Comment by cpmbwo** [comment]
U r welcome.
