### ISSUE TITLE
这个时候XX-Mini-P3版居然可以观看1080

### ISSUE THREAD

**Issue by xyuanmu** [xyuanmu/XX-Mini#39]
今天无意中测试 XX-Mini python3版本，惊人的发现，用现在能搜索到的IP居然可以观看1080，而python2版本看480都在缓冲，原理还不清楚，大家可以试试，看那个进度条缓冲的长度，太不可思议了：
![xx-mini-p3](https://cloud.githubusercontent.com/assets/12442896/14229689/b0438656-f96c-11e5-857e-03b3880d6f8a.png)
![xx-mini-p3-2](https://cloud.githubusercontent.com/assets/12442896/14229701/1eab96ba-f96d-11e5-8c2c-7d2187eecf4a.png)

Windows： https://drive.google.com/file/d/0B4lIa3JGSHbQV1J1R3I1NXBJUG8/view
Linux： https://github.com/xyuanmu/XX-Mini/archive/python3.zip
IP段用这份：https://github.com/XX-net/XX-Net/issues/2636#issuecomment-204737284 ，建议用 [checkiptools](https://github.com/xyuanmu/checkiptools) 先扫描一遍，提取IP段。

当然，python3版本还在测试，一些python2版本有的功能还没加进去，等有时间整理下，也欢迎大家反馈问题。另外提醒一句，XX-Mini是提取自XX-Net，如果无法/不会使用，可以先用 [XX-Net python3](https://github.com/XX-net/XX-Net/tree/python3) 版测试。

**Comment by xyuanmu** [comment]
![xx-mini-p3-3](https://cloud.githubusercontent.com/assets/12442896/14229761/2b09029c-f96f-11e5-8db8-7ee0f95280be.png)
30分钟的视频已经测试完毕，流畅播放，没任何问题。
附上视频地址：https://www.youtube.com/watch?v=0wCC3aLXdOw

**Comment by xyuanmu** [comment]
![xx-mini](https://cloud.githubusercontent.com/assets/12442896/14230294/306e4828-f983-11e5-9cf4-7bae5d500b11.png)
好吧，刚才测试了下1.2.4版本，照样可以1080P，看来IP有解封的趋势，并不是python3的功劳。

**Comment by Lovefish** [comment]
你的console怎么有绿色?

**Comment by xyuanmu** [comment]
@Lovefish  打开proxy.ini，[listen] debuginfo = 1，就能显示绿色的日志了。

**Comment by Lovefish** [comment]
@xyuanmu 多谢, 今天才知道...

**Comment by jzp820927** [comment]
今天才知道，原来日志颜色，还有开关。

**Comment by xyuanmu** [comment]
@jzp820927 不是颜色开关:grin:，debug是最低级的日志，一般调试的时候看的。

**Comment by jzp820927** [comment]
也就是说，不开调试，日志就没颜色？开了调试才有？
我记得好像 good ip 和 bad ip 也有颜色吧？
