### ISSUE TITLE
我现在关心的是 linux 版，啥时候实现 egg 打包库文件？

### ISSUE THREAD

**Issue by jzp820927** [xyuanmu/XX-Mini#4]
如题，我现在关心的是 linux 版，啥时候实现 egg 打包库文件？

**Comment by xyuanmu** [comment]
可以实现，发现用压缩包添加引导文件__genpy__.py，然后改后缀即可。

**Comment by xyuanmu** [comment]
打包了一个版本：https://github.com/xyuanmu/XX-Mini/releases/download/1.0/XX-Mini_linux_v1.0.zip
测试的系统是ubuntu

**Comment by jzp820927** [comment]
@xyuanmu 高手在民间，我马上测试

**Comment by jzp820927** [comment]
@xyuanmu 不错，不错，测试完美无缺，感谢 @xyuanmu 君，以后就用这个版本了。
