### ISSUE TITLE
youtube

### ISSUE THREAD

**Issue by wangfeng87** [xyuanmu/XX-Mini#43]
新版python3看youtube暂停一会就出错

**Comment by xyuanmu** [comment]
终端报错还是视频报错？

**Comment by jzp820927** [comment]
把你出错的视频地址贴出来，我来测试一下

**Comment by wangfeng87** [comment]
![image](https://cloud.githubusercontent.com/assets/10720688/14232898/acbacd54-f9ea-11e5-8323-35da89263e37.png)

**Comment by wangfeng87** [comment]
暂停一会就会出现这个界面
以前就不会

**Comment by xyuanmu** [comment]
视频传输中断，看看终端里有没有提示 no enough ip，python3传输个人觉得比2要稳定，应该不会突然中断。

**Comment by wangfeng87** [comment]
IP足够了，不暂停没事，暂停缓冲一会就出问题

**Comment by wangfeng87** [comment]
可能是我的chrome有问题

**Comment by jzp820927** [comment]
那你换 firefox 试试不就知道是不是 chrome 的问题了

**Comment by xyuanmu** [comment]
刚才试了那个视频，视频没问题，可以一直缓冲到结束，换别的浏览器试试。
![y2b](https://cloud.githubusercontent.com/assets/12442896/14232957/744ded82-f9ec-11e5-8f9a-c29a81eb6274.png)

**Comment by wangfeng87** [comment]
应该是chrome问题了，同时开多个标签页，后台的页面会暂停，不知道为什么，重装就好了

**Comment by jzp820927** [comment]
好像这是 chrome 浏览器的新特性，除当前活动 tab 的其他后台 tab 的多媒体会暂停，你是把 youtube 的播放放到后台去了？

**Comment by wangfeng87** [comment]
依然是昨天那个问题，并不是浏览器的问题，用XXNET就没问题，
