### ISSUE TITLE
网络不通会造成有效ip损失

### ISSUE THREAD

**Issue by abchb99** [xyuanmu/XX-Mini#49]
有时本地连接虽然是连着，但是百度是不通的，任何外网都不通。这个情况XX-Net可以判断出来，因为在管理界面看到提示网络连接有问题，这时所有good ip都保留，并不会减少，而XX-Mini会逐步减少good ip直到0，如果网络恢复了，又从0开始扫描。
可能是精简掉了网络判断的部分吧。

**Comment by yeahwu** [comment]
还有一个问题，关于扫描线程数能不能像xx一样，设为自动

**Comment by xyuanmu** [comment]
刚才测试了一下，只是终端日志显示good ip少了而已，good_ip.txt 并没有IP会掉，找时间再看看是哪里计算出错了，谢谢你的反馈。

**Comment by xyuanmu** [comment]
@yeahwu 扫描线程默认就是自动调整的。

**Comment by yeahwu** [comment]
哪如果手动设置了线程以后，也就不会自动调整了？

**Comment by xyuanmu** [comment]
@yeahwu 会，计算公式如下：
(第100个IP的延时 - 200) ÷ 2 * 最大扫描线程 ÷ 50

**Comment by yeahwu** [comment]
谢谢解惑

**Comment by jzp820927** [comment]
其实手动设置的扫描线程，只是设置的最大扫描线程，不是固定扫描线程

**Comment by yeahwu** [comment]
其实这样也算合理，延迟越大，线程就越大。很好

**Comment by yeahwu** [comment]
不得不说，mini在linux上用的比xx省心，开机自动启动，图标啥的比较全，赞一个

**Comment by xyuanmu** [comment]
已查明，此问题只出现在 python3 版，而且XX-Net的python3版本也有此问题，原因是 check_ip 重设网络检测的时间和状态，这个功能在python2中没问题但是在python3中会出问题。

**Comment by abchb99** [comment]
是的，
测试了一下python2，网络不通了，显示的good ip减少10个后，提示网络有问题，就不再减少了，恢复网络，再关闭、重新运行python2的XX-Mini，那减少的10个又回来了，并不是真的减少。
