### ISSUE TITLE
原版支持局域网pac，麻烦加上

### ISSUE THREAD

**Issue by newcastlecy** [xyuanmu/XX-Mini#5]
支持pac自动代理的设置为 http://127.0.0.1:8086/proxy.pac
[pac]
ip = 0.0.0.0

可以写成 对应的ip
如  http://192.168.1.5:8086/proxy.pac

**Comment by xyuanmu** [comment]
XX-Mini配置后没效果吗？

**Comment by xyuanmu** [comment]
刚才测试了下，8087和8086端口都没效果，我抽空研究看看。

**Comment by xyuanmu** [comment]
晕死，我自己失误了，被系统防火墙K了，可以使用的，data目录新建一个 manual.ini，输入下面内容即可：
```
[pac]
ip = 0.0.0.0

[listen]
ip = 0.0.0.0

**Comment by newcastlecy** [comment]
增加了
[listen]
ip = 0.0.0.0 
好像还是不行，怎么添加系统防火墙、、？

**Comment by xyuanmu** [comment]
改了以后运行 goagent.exe 防火墙应该会提示的，如图，点允许访问：
![firewall](https://cloud.githubusercontent.com/assets/12442896/13747650/3d8cc89e-ea34-11e5-8df8-35482a8a0dc5.png)

如果没提示，到开始菜单输入 **防火墙**，打开  Windows 防火墙 - 允许程序或功能通过 Windows 防火墙里找到 python27(goagent) 勾选上。

**Comment by jzp820927** [comment]
我一般都是把防火墙直接关了，一了百了。

**Comment by newcastlecy** [comment]
xxnet在防火墙里有，mini没有，
![image](https://cloud.githubusercontent.com/assets/3032427/13766230/093a6e9a-ea9b-11e5-80bb-9a96621e7ad0.png)
127.0.0.1正常
![image](https://cloud.githubusercontent.com/assets/3032427/13766236/11f23446-ea9b-11e5-8921-ec0ff4eb1079.png)

192.168.1.115打不开
![image](https://cloud.githubusercontent.com/assets/3032427/13766246/2723d02c-ea9b-11e5-88f7-384cc5390abd.png)

**Comment by xyuanmu** [comment]
@newcastlecy 那就手动添加吧

**Comment by newcastlecy** [comment]
@xyuanmu 加了也不行，原版是没问题的，不晓得是哪里精简了

**Comment by newcastlecy** [comment]
@xyuanmu  问题找到了# manual.ini未生效，修改proxy.ini 正常了！！！

**Comment by xyuanmu** [comment]
奇怪，怎么都说manual未生效，你 manual,ini 后缀是 ini 还是 txt ？

**Comment by newcastlecy** [comment]
@xyuanmu ini
