### ISSUE TITLE
关于证书问题。

### ISSUE THREAD

**Issue by yeahwu** [xyuanmu/XX-Mini#51]
由于很积极滴追逐每个版本，发现一个大问题。因为本人对安全还是很重视滴，所以关于安全的问题都是“大问题”！
用的是linux，火狐，发现每次重新配置新版mini都不用重新删除证书，导入证书，打开即用，方便是很方便，但这不科学呀！
一个老证书用到死，这无疑是不安全的嘛！
对比了一下叉烧狗，则没有这个问题，每次都要重新导入，这让俺很安心。

**Comment by heiheihei120** [comment]
不明觉厉 大大好！路过帮顶   ：）

**Comment by wz7465** [comment]
全新安装自动生成导入证书，升级延用证书，很好的设定，完全多虑了，不安心，手动更换即可

**Comment by yeahwu** [comment]
这升级和全新安装有什么区别？何来全新安装和升级？
wz <notifications@github.com>于2016年4月16日 周六08:03写道：

**Comment by wz7465** [comment]
？如果你系统里从没安装过mini. 第一次解压运行的时候，不是自动生成证书并导入浏览器的么？这个证书每个使用者都不一样，安全性是有保障的。这不同于早期的 goagent 使用的都是同一证书

**Comment by yeahwu** [comment]
mini是每次更新都需要重新安装的。简单点讲，每次安装俺都是让其自动生成ca证书。问题是这每次重新生成的证书都不用重新导入？
俺怀疑这mini是不是都在用一个证书？
wz <notifications@github.com>于2016年4月16日 周六08:39写道：

**Comment by yeahwu** [comment]
@xyuanmu 你可以试试删除data文件夹下的两个证书文件，然后重启mini和浏览器。

**Comment by xyuanmu** [comment]
@yeahwu 试过了，删掉证书，重新生成新证书，火狐提示：安全连接失败。

**Comment by yeahwu** [comment]
难道是俺一直以来的错觉？还是，xx已经支持火狐证书自动导入了？xx-net也是这样。
你们火狐每次重新安装都不用导入证书的？

**Comment by yeahwu** [comment]
难道是俺一直以来的错觉？还是，xx已经支持火狐证书自动导入了？xx-net也是这样。
你们火狐每次重新安装都不用导入证书的？

**Comment by yeahwu** [comment]
俺这电脑无敌了，删除证书文件，然后重新生成都不用重新导入的，直接用，xx和mini都不用
难道是linux的问题？

**Comment by xyuanmu** [comment]
也许吧，win下每次生成的证书都不同，你可以对比下两次生成的md5是否一直。

**Comment by yeahwu** [comment]
惊奇地发现，md5不一致。也就是说，证书被自动替换鸟，还是大火狐。

**Comment by wz7465** [comment]
XX-Mini_win_v1.2.2
证书创建日期 2016-03-30 15.54


通用名GoAgent XX-Mini
组织GoAgent
组织单元 GoAgent Root
序列号 00
开始于2016年3月30日
过期时间2026年3月30日

SHA-256指纹AD:BA:AD:A3:47:B0:99:3C:54:41:0E:B4:61:32:BB:96:57:A9:EB:4F:C5:24:5F:B2:6D:D2:EF:CA:78..
SHA1 指纹 96:C3:0E:79:0D:EB:C0:73:23:51:4B:51:80:4E:F9:E0:C0:BD...

---------------------------------------
严格测试过程（Windows系统）

我的原先XX-Mini_win_v1.2.2
下载XX-Mini_win_v1.2.3，放到原来位置并改名为XX-Mini_win_v1.2.2文件夹
初始解压后，里面是没有data文件夹的

运行，提示已经导入GoAgent证书，请重启浏览器
重启火狐浏览器（我的默认浏览器）后，查看证书，发现没变化，有效期和指纹完全一致

删除data文件夹，并删除浏览器中的证书，关闭浏览器，重启后确认证书已经删除
重启XX-Mini后，提示又导入证书，但是发现浏览器中没有这个证书，手动导入，这回证书更新了，日期和指纹都变了
查看explorer浏览器，发现证书全都导入到这里了，这就是问题所在

结论：XX-Mini能自动生成和导入证书，默认浏览器是explorer，火狐无效

**Comment by yeahwu** [comment]
你就试试删除mini的data文件夹下的证书 certs和ca文件，浏览器里的证书不要管它。
然后重启浏览器和mini，看看能不能连上外网

**Comment by yeahwu** [comment]
@xyuanmu 兄，弱弱地问一句，你这个新ip段，可用ip大概有多少哇？大概

**Comment by xyuanmu** [comment]
@yeahwu 还没整体扫过，最少3百吧，包含了你分享的那份。

**Comment by yeahwu** [comment]
哦，俺看要不要提交给xx？gae没ip也是个梗哪！

**Comment by jzp820927** [comment]
如果 证书被自动导入 IE 了，也就是系统证书，chrome 就可以直接信任，但是 firefox 的证书系统是独立于系统证书的，所以要单独导入。

**Comment by yeahwu** [comment]
@jzp820927 不可思议的是俺这火狐的证书就是自动替换了，xx和mini都试过，不用手动导入

**Comment by yfdyh000** [comment]
@yeahwu https://github.com/xyuanmu/XX-Mini/blob/839343a941ac7ecda19f65f89cc9cdf27219a6a9/lib/cert_util.py#L454

**Comment by yeahwu** [comment]
@yfdyh000 看来是为debian（大便）用户量身定做滴！

**Comment by yfdyh000** [comment]
@yeahwu import_linux_firefox_ca 也有啊。

**Comment by yeahwu** [comment]
目前看来，就俺成功了，哈哈哈

**Comment by jzp820927** [comment]
意思是说，Linux 和 firefox 都可以自动导入证书？这也太牛B了吧

**Comment by yfdyh000** [comment]
不是一直如此吗，我没试过，从代码上看应该是支持的。

**Comment by jzp820927** [comment]
一直是备份老证书在用，好多年没生成新证书导入过了，没注意这个问题

**Comment by yeahwu** [comment]
win是不支持的，linux下俺看也就dabian一支支持，所以ubuntu，linuxmint啥的应该没啥问题
