### ISSUE TITLE
开机启动

### ISSUE THREAD

**Issue by wangfeng87** [xyuanmu/XX-Mini#53]
怎么关闭开机启动啊

**Comment by xyuanmu** [comment]
什么系统？Windows的话，开始菜单 - 所有程序 - 启动，删掉goagent即可。

**Comment by wangfeng87** [comment]
哦，设置开机启动后，goagent是在后台运行的，那个框框不显示

**Comment by xyuanmu** [comment]
重新添加启动项，询问托盘图标的时候点是/确认，点击托盘图标即可显示cmd窗口。
