### ISSUE TITLE
github回复时提示 Something went wrong with that request. Please try again

### ISSUE THREAD

**Issue by sishentibu** [xyuanmu/XX-Mini#54]
用xx-mini回复时会有这个提示，用goproxy则无问题
这个是我用的ip有问题，还是程序问题？

**Comment by jzp820927** [comment]
能用就行了吧，管他提示神马

**Comment by sishentibu** [comment]
不能用。浏览器上弹出这个提示，然后comment按钮变灰了。信息却发不出去

**Comment by jzp820927** [comment]
那就多贴点日志出来看看

**Comment by sishentibu** [comment]
以下为日志内容
------------------------------------
--------------------------------------------------------------------------------
XX-Mini Version     : 1.2.5 (python/2.7.11 pyopenssl/16.0.0)
Listen Address      : 127.0.0.1:8087
Setting File        : manual.ini/proxy.ini
Pac Server          : http://127.0.0.1:8086/proxy.pac
CA File             : http://127.0.0.1:8086/CA.crt
Pac File            : file://D:\proxy\XX-Mini\data\proxy.pac
--------------------------------------------------------------------------------
Apr 19 21:16:00.647 - [INFO] SSL use version:TLSv1_2
Apr 19 21:16:00.984 - [INFO] load ip range file:D:\proxy\XX-Mini\data\ip_range.txt
Apr 19 21:16:01.058 - [INFO] load google ip_list num:189, gws num:189
Apr 19 21:16:01.059 - [INFO] good ip num:116, bad ip num:73
Apr 19 21:16:01.392 - [INFO] server 127.0.0.1:8087 started.
Apr 19 21:16:01.393 - [INFO] server 127.0.0.1:8086 started.
Apr 19 21:16:01.397 - [INFO] PACServer from:127.0.0.1:52973 GET /proxy.pac
Apr 19 21:16:01.428 - [INFO] GAE CONNECT api.github.com:443
Apr 19 21:16:01.585 - [INFO] GAE CONNECT live.github.com:443
Apr 19 21:16:02.161 - [INFO] GAE CONNECT github.com:443
Apr 19 21:16:02.406 - [WARNING] Method OPTIONS not support in GAEProxy for https://api.github.com/_private/browser/stats
Apr 19 21:16:03.192 - [INFO] GAE CONNECT live.github.com:443
Apr 19 21:16:03.422 - [INFO] good ip num:116, bad ip num:73
Apr 19 21:16:03.607 - [INFO] GAE 1656|45.64.76.15|1185 t:1187 s:31415 hs:338 Spd:173563 200 https://github.com/xyuanmu/XX-Mini/suggestions/issue/149451228
Apr 19 21:16:03.619 - [INFO] good ip num:116, bad ip num:73
Apr 19 21:16:03.622 - [INFO] GAE 1692|59.18.46.55|253 t:394 s:0 hs:340 200 https://live.github.com/_sockets/MTM4MzIxODI6Mzg5NDI1NzA2YjM0MzM4ODVjY2EwZGZhMTMwYzE2OGI6ZmYxNjE2YWFmMzI4ZTA2MjhjNTNlMjdhN2U3MWE4ZDQxMWM3YjIyYTdmODU2YzI2YjViMGUxNzk5OGVlNzk0Mg==--bbd914c9cf02aaec9e46a370f9e3b7359333c288
Apr 19 21:16:09.804 - [INFO] GAE CONNECT github.com:443
Apr 19 21:16:10.298 - [INFO] good ip num:114, bad ip num:75
Apr 19 21:16:10.301 - [INFO] GAE 1656|45.64.76.15|33505 t:481 s:8974 hs:338 Spd:8972511 422 https://github.com/xyuanmu/XX-Mini/issue_comments
Apr 19 21:16:10.347 - [INFO] GAE CONNECT api.github.com:443
Apr 19 21:16:10.349 - [INFO] GAE CONNECT api.github.com:443
Apr 19 21:16:10.746 - [INFO] good ip num:114, bad ip num:75
Apr 19 21:16:10.749 - [INFO] GAE 1692|59.18.46.55|697 t:374 s:99 hs:340 400 https://api.github.com/_private/browser/errors
Apr 19 21:16:10.828 - [INFO] good ip num:114, bad ip num:75
Apr 19 21:16:10.829 - [INFO] GAE 1656|45.64.76.15|42922 t:460 s:99 hs:338 400 https://api.github.com/_private/browser/errors
Apr 19 21:16:11.960 - [INFO] GAE CONNECT live.github.com:443
Apr 19 21:16:12.517 - [INFO] good ip num:114, bad ip num:75
Apr 19 21:16:12.521 - [INFO] GAE 1656|45.64.76.15|43276 t:534 s:0 hs:338 200 https://live.github.com/_sockets/MTM4MzIxODI6Mzg5NDI1NzA2YjM0MzM4ODVjY2EwZGZhMTMwYzE2OGI6ZmYxNjE2YWFmMzI4ZTA2MjhjNTNlMjdhN2U3MWE4ZDQxMWM3YjIyYTdmODU2YzI2YjViMGUxNzk5OGVlNzk0Mg==--bbd914c9cf02aaec9e46a370f9e3b7359333c288
Apr 19 21:16:29.050 - [INFO] GAE CONNECT live.github.com:443
Apr 19 21:16:34.067 - [INFO] good ip num:114, bad ip num:75
Apr 19 21:16:34.069 - [INFO] GAE 1620|202.220.161.173|254 t:31651 s:0 hs:249 200 https://live.github.com/_sockets/MTM4MzIxODI6Mzg5NDI1NzA2YjM0MzM4ODVjY2EwZGZhMTMwYzE2OGI6ZmYxNjE2YWFmMzI4ZTA2MjhjNTNlMjdhN2U3MWE4ZDQxMWM3YjIyYTdmODU2YzI2YjViMGUxNzk5OGVlNzk0Mg==--bbd914c9cf02aaec9e46a370f9e3b7359333c288

**Comment by xyuanmu** [comment]
这个回复是通过mini全局代理回复的，问一下，是python3还是python2版本有这个提示。

**Comment by sishentibu** [comment]
Python2
1.2.5

**Comment by xyuanmu** [comment]
看日志你应该有上传附件，gae不支持Method OPTIONS，所以按钮变灰。

**Comment by sishentibu** [comment]
难道是后台上传？应该也不会啊
就比如在这个issue中，我纯文字输入，然后按ctrl+enter，就会出现这个提示了
win10 x64

**Comment by jzp820927** [comment]
@sishentibu话说，github 又没墙，没必要走代理吧？

**Comment by xyuanmu** [comment]
换一个浏览器试试看？

**Comment by sishentibu** [comment]
因为我这边从浏览网页速度来看，挂代理比较快

**Comment by sishentibu** [comment]
@xyuanmu 待我试试ie

**Comment by sishentibu** [comment]
@xyuanmu ie没搞出来，换chrome试了
登录github就出错了
http://i3.piimg.com/160dd9f5f1a5e320.png
xx-mini信息 
[登录.txt](https://github.com/xyuanmu/XX-Mini/files/226129/default.txt)

然后评论后仍然有问题
http://i3.piimg.com/130ab3ba209c4b4d.png
xx-mini 信息
[评论后.txt](https://github.com/xyuanmu/XX-Mini/files/226132/default.txt)
评论后，xx-mini的信息一直在刷屏，我只是复制了部分

**Comment by xyuanmu** [comment]
奇怪，为什么你的浏览器都会通过Options方式访问 https://api.github.com/_private/browser/stats ，我想这应该是源头，暂时先别用代理访问GitHub，因为我这边问题没有复暂时现查不出是哪里的原因，抱歉！

**Comment by sishentibu** [comment]
是不是我设置的问题？
我是新建了个manual.ini，除了gae段，其余内容如下
[google_ip]
auto_adjust_scan_ip_thread_num = 1
max_scan_ip_thread_num = 5
max_good_ip_num = 1000

[system]
;设置成 1 会在data目录生成日志文件 local.log，便调试用
log_file = 0
;设置是否在data目录输出扫描IP日志 scan_ip.log，超过3000行会新建日志
log_scan = 0


另，不仅仅是这个问题，Google讨论组，如 https://groups.google.com/forum/#!forum/fqlt 就会提示无法加载，换用goproxy就可以。感觉我这边存在问题

**Comment by sishentibu** [comment]
@xyuanmu 我想起来了，是不是gae服务器端的问题。
因为最近用goproxy的时候，有更新过服务器端，用的是go的服务器端。
我明天试试能不能用旧的gae服务器端重新上传，因为隐约有看到旧的上传端口被Google关闭了

**Comment by jzp820927** [comment]
goproxy 的服务器还不完善，你 XXNET 的服务端试试

**Comment by xyuanmu** [comment]
我曾经部署过go的server.gae，结果发现在xx-net内用有问题，连谷歌都登录不了，如果是在mini或net中使用的appid建议用新版xx-net重新部署。

**Comment by jzp820927** [comment]
P大，已经说了，以后会兼容，XXNET，和 goagent 的客户端，到时候，再部署 go 服务端也不迟。

**Comment by sishentibu** [comment]
可以部署，但是用这个部署怎么加密码？
就是旧gae上传的时候可以设个密码，不知道密码的话，就算知道appid也不能用

**Comment by xyuanmu** [comment]
部署后会覆盖代码，根本不需要密码

**Comment by sishentibu** [comment]
@xyuanmu 成功加上密码上传完成
而且这个就是用的xx-mini回复的
看来果然是服务器端的问题
