### ISSUE TITLE
有人尝试过在hiwifi上安装吗？

### ISSUE THREAD

**Issue by linweijun** [xyuanmu/XX-Mini#59]
手上有极1s，最近发现官方论坛上有关于开发工具的介绍，其中提到了python2.7但是他说只能在极路由上使用，所以我想问问有没有人搞过呢？

**Comment by hwx7hao** [comment]
我试过，但同时挂Dr.Com时会死掉，估计是内存不足，（用的是极二）

**Comment by linweijun** [comment]
@hwx7hao 好吧，看来不行的，我还以为搭个局域网的代理。
