### ISSUE TITLE
manual.ini未能生效，xx-mini照常引用公共appid，无法看视频

### ISSUE THREAD

**Issue by yuan78** [xyuanmu/XX-Mini#6]
manual.ini未能生效，xx-mini照常引用公共appid，无法看视频。

手动生成manual.ini放置在data目录下，按照参照的格式写入并填入自己的APPID,但是xx-mini照常引用公共appid，无法看视频。

**Comment by xyuanmu** [comment]
启动 goagent.exe 开头有没有输出 load manual.ini success，没有说明格式有误。

**Comment by yeahwu** [comment]
试试启动前，在proxy.ini文件里把xx的id替换成自己的。简单点讲也就是删除data文件，修改proxy.ini，不用创建manual.ini文件夹，再启动。@yuan78应该是gary12吧？

**Comment by yuan78** [comment]
@xyuanmu, 提一点建议：config.py里面建议加上对manual.ini.txt的识别，具体原因相信你能明白。

 lib/config.py
Showing the top four matches. Last indexed 2 days ago.
                self.CONFIG.readfp(io.BytesIO(content))

        # load ../../../data/manual.ini, set by manual
        self.CONFIG_MANUAL_FILENAME = os.path.abspath( os.path.join(self.DATA_PATH, 'manual.ini'))

**Comment by newcastlecy** [comment]
manual.ini v1.2 好像还是不生效

**Comment by xyuanmu** [comment]
你是放到data目录吗？启动的时候把最前面横杠里的日志复制下来，appid可以去掉。如果不知道怎么复制，打开 proxy.ini 最下面的 [system] log_file = 1，启动后到data目录找到 local.log 把前面横杠的日志复制出来。

**Comment by newcastlecy** [comment]
原来放错位置了

**Comment by tinyhugh** [comment]
@newcastlecy 编码不对也读取不到

**Comment by xyuanmu** [comment]
@tinyhugh ANSI编码一般只用在Windows中文系统里的gbk编码，用utf-8在cmd里会乱码，而在Linux系统中默认都是utf-8格式，所以ini文件里最好还是别用中文。

**Comment by tinyhugh** [comment]
@xyuanmu 怪不得proxy.ini中没有中文提示
