### ISSUE TITLE
ubuntu 16 怎么用？

### ISSUE THREAD

**Issue by jdfq** [xyuanmu/XX-Mini#74]
终端运行 python proxy.py 后显示：
Traceback (most recent call last):
  File "proxy.py", line 63, in <module>
    from OpenSSL import version as openssl_version
ImportError: No module named OpenSSL

**Comment by jzp820927** [comment]
https://github.com/xyuanmu/XX-Mini/wiki/No-module-named-OpenSSL

**Comment by jdfq** [comment]
已经搞定，谢谢。
