### ISSUE TITLE
xyuanmu 兄，可否指点一下，如何加入goagent 的认证功能?

### ISSUE THREAD

**Issue by jzp820927** [xyuanmu/XX-Mini#8]
goagent 有用户，密码认证功能，如何在 mini 版加入这个认证功能？以前在 xxnet 的issuse 提过，作者说不考虑加认证，因确实有这个需要，可否请  xyuanmu 兄，指点一下？具体需要加入哪些代码？

**Comment by xyuanmu** [comment]
密码认证，刚才查看了下代码，这个功能好复杂，我得找个时间研究下，不保证可以实现。

**Comment by xyuanmu** [comment]
对了，能不能说明下这个功能是有什么用的？我还不知道有这个功能。

**Comment by jzp820927** [comment]
就是 http basic 认证啊，比如我想分享这个代理到公网，对方要先输入用户，密码才能使用这个代理。简单点，也就是分享给别人的时候，防止被滥用。

**Comment by xyuanmu** [comment]
明白了。
在GoAgent里面，控制这个代码在 proxy.py 1604 行：
```
GAEProxyHandler.handler_filters.insert(0, AuthFilter(common.LISTEN_USERNAME, common.LISTEN_PASSWORD))
```
直接加过滤功能到网络处理里面，xx-net 好像没有类似的功能，我 python 并不是很熟，要加我也不知该从哪里入手。

**Comment by jzp820927** [comment]
好吧，如果有时间的话，就麻烦你研究下，实在不行就算了。我是对 py 一点基础都不了解，不太分析的懂源码。

**Comment by sishentibu** [comment]
gee的这段也有个密码，不也是防止滥用的吗？
[gae]
enable = 1
appid = 
password =

**Comment by jzp820927** [comment]
@sishentibu 这个2个密码的作用不一样，如果是分享到公网的话，这个密码就没有用。

**Comment by sishentibu** [comment]
@jzp820927 这个公网指的是局域网吧？这个我确实没用过
我只是碰到ID被人用了，然后自己在gae段加了密码。所以以为是同样的情况

**Comment by jzp820927** [comment]
我说的情况是 监听 0.0.0.0，给局域网，或者外网使用。

**Comment by sishentibu** [comment]
恩，理解了。
但是要等会的来解决了。我不懂代码。。

**Comment by jzp820927** [comment]
这个是从 XX 精简来的，而 XX 本身又没有移植认证功能的代码过来，所以只能看有没有懂得人提交代码了

**Comment by sishentibu** [comment]
好吧，不展开讨论了。
你可以试试@  可能懂的来看看

**Comment by xyuanmu** [comment]
@jzp820927 仔细查看了 GoAgent 代码几遍，终于了解该功能是如何实现的。
首先向浏览器发出407代理认证请求，然后获取base64加密的帐号密码信息，解码后与本地的进行比对，如果一致就可通过代理认证。GoAgent 的filter真的很有条理，分析了好久才分析出来的，终于实现这个功能了，已经发布1.2版本，欢迎测试！

**Comment by jzp820927** [comment]
@xyuanmu 兄幸苦了，不愧是民间高手，之前我都是在 xxmini 前面再套一个 cow 来认证，看来现在可以去掉 cow 了，直接用 xxmini 了，兄弟我跪谢了。

**Comment by xyuanmu** [comment]
@jzp820927 不客气
