### ISSUE TITLE
openwrt上运行失败

### ISSUE THREAD

**Issue by OvlTkm** [xyuanmu/XX-Mini#89]
```
root@Home:/usr/lib/XX-Mini# python proxy.py
Traceback (most recent call last):
  File "proxy.py", line 63, in <module>
    from OpenSSL import version as openssl_version
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: File not found
```
对这个不是很懂，表示茫然←_←
哪位大神来帮我让它运行起来......
谢谢！

**Comment by 523860169** [comment]
同样的问题

**Comment by jzp820927** [comment]
好像是 openssl 的相关库没安装

**Comment by OvlTkm** [comment]
请问具体要怎么做呢

**Comment by jzp820927** [comment]
pyopenssl  安装这个试试，或者 python-openssl

**Comment by OvlTkm** [comment]
嗯我這裡已經安裝了Python-pyOpenSSL和Python-OpenSSL…

**Comment by jzp820927** [comment]
https://github.com/xyuanmu/XX-Mini/wiki/OpenWrt-%E4%B8%8B%E9%85%8D%E7%BD%AE-XX-Mini
查考下这个

**Comment by OvlTkm** [comment]
我重装了python和相关的软件包，可是……出现了更离奇的情况
```
root@Home:~# python
-ash: python: not found
```

**Comment by jzp820927** [comment]
python 的运行命令都没有，这个肯定不行

**Comment by OvlTkm** [comment]
也不清楚是为什么……明明装了python

**Comment by OvlTkm** [comment]
也不清楚是为什么……明明装了python

**Comment by jzp820927** [comment]
搜索下 python 命令的路径，是不是在 path 变量内。

**Comment by OvlTkm** [comment]
最近这段时间事情比较多，加上之前鼓捣这个也花了几天时间都没有成功所以就暂时搁置了，也没有打声招呼就直接消失，实在是对不住。
今天总算又打起精神回来接着干。我重装了最新的openwrt snapshot固件，按照 天朝屁民 在上面给出的wikipage教程依次安装了python 和pyopenssl, python-opensssl，这次运气极佳（或许是刚装完固件整个系统都是新的，没有其他因素干扰吧）三项软件包及依赖包等都顺利安装无报错。这里表示十分感谢 @jzp820927 和写wikipage的 @yangjian226200 
但让我感到奇怪的是在我的软件源中pyopenssl的包名其实是python-pyopenssl，所以安装的时候opkg命令需要相应改动。不过值得高兴的是这并没有影响什么，软件包安装成功后XX-Mini成功启动。
非常感谢你们的帮助。

**Comment by jzp820927** [comment]
恭喜发财，红包拿来。
