### ISSUE TITLE
下载的问题。

### ISSUE THREAD

**Issue by distance00** [xyuanmu/XX-Mini#98]
用XX-Net可以正常下载，用XX-Mini就不行，一下载cpu占用率暴增，没有任何速度。
https://www.google.com/dl/release2/11hmxyrthwo6sfa4srooxoxwf5djo6vm3g4xz55xqjx1p3e97t44w51ulpwyokjwbc61nqxg60rezh5ifpwersjblmur7yr9c07k/53.0.2785.80_chrome_installer.exe

**Comment by jzp820927** [comment]
不科学吧，CPU 的问题，一般只出现在 路由上

**Comment by distance00** [comment]
@jzp820927 能否帮忙试下你用XX-Mini能否正常下载？

**Comment by jzp820927** [comment]
行吧，我帮你测试下。

**Comment by distance00** [comment]
日志就一句：
[INFO] GAE CONNECT www.google.com:443
XX-Net正常，XX-Mini核心和XX-Net不是完全一样吗？

**Comment by jzp820927** [comment]
确实是一样的，挺奇怪的，不知道是不是 IP 的问题，我再试试，直接打开 www.google.com 都没问题，就这个地址没反应。

**Comment by samho88** [comment]
我用XXMINI在路由上运行，下载没有问题

**Comment by distance00** [comment]
@samho88 下载这个呢？
https://www.google.com/dl/release2/gkyfcwolp6glt51i6mh6r7rb49r372ey93fur2cwm77e4qwcdprgwtxdtr54y0mty95cnsb53yqzerygps4m19clla1phu3pg9j/53.0.2785.89_chrome_installer.exe

**Comment by samho88** [comment]
也可以下载啊，不过速度不快，只有500-600K

**Comment by abchb99** [comment]
我用的XX-Mini v1.2.6，装在64位win8.1中，这两个链接都可以正常下载，速度正常，cpu没有异常啊。

**Comment by distance00** [comment]
我用的chrome + Proxy SwitchyOmega，不知道上面能下载的用的什么浏览器？

**Comment by jzp820927** [comment]
我刚刚测试了下，还是不能用代理下载，奇怪

**Comment by abchb99** [comment]
Firefox40，代理用的AutoProxy 0.4b2.2015031118，刚才又试了，可以正常下载。

**Comment by distance00** [comment]
比较一下，似乎就[hosts]部分有所区别，完全复制过来，还是一样的，无法下载，又试了firefox48也一样。

**Comment by jzp820927** [comment]
挺奇怪的，按理说，不应该出现这样的问题，我再用 XXNET 试试能不能下载

**Comment by abchb99** [comment]
我试了下XX-Mini v1.2.7，也是不能下载，看来这个版本有bug。

**Comment by samho88** [comment]
就是用360浏览器来自我的华为手机-------- 原始邮件 --------主题：Re: [xyuanmu/XX-Mini] 下载的问题。 (#98)发件人：distance00 收件人：xyuanmu/XX-Mini 抄送：samho88 ,Mention 我用的chrome + Proxy SwitchyOmega，不知道上面能下载的用的什么浏览器？

**Comment by jzp820927** [comment]
你的意思是 XX-Mini v1.2.6 下载没有任何问题，XX-Mini v1.2.7 不能下载。

**Comment by abchb99** [comment]
是的，XX-Mini v1.2.6 正常下载，XX-Mini v1.2.7 不能下载。

**Comment by jzp820927** [comment]
诡异，如果有闲心的话，可以对比一下，1.2.6 和 1.2.7 之间的代码变化，手动改一下

**Comment by distance00** [comment]
确实很诡异，同一个文件，同样是google的网站。dl.google.com可以下载
https://dl.google.com/release2/gkyfcwolp6glt51i6mh6r7rb49r372ey93fur2cwm77e4qwcdprgwtxdtr54y0mty95cnsb53yqzerygps4m19clla1phu3pg9j/53.0.2785.89_chrome_installer.exe
但www.google.com无法下载。
https://www.google.com/dl/release2/gkyfcwolp6glt51i6mh6r7rb49r372ey93fur2cwm77e4qwcdprgwtxdtr54y0mty95cnsb53yqzerygps4m19clla1phu3pg9j/53.0.2785.89_chrome_installer.exe

**Comment by jzp820927** [comment]
我这边刚刚又试了一下，又可以了，不知道是什么原因

**Comment by abchb99** [comment]
我这儿1.2.7还是不能下载。

**Comment by jzp820927** [comment]
诡异的问题，影响不大

**Comment by xyuanmu** [comment]
确实有问题，http/2模式下不支持直连，打开 proxy.ini 中修改35行，在开头加一个半角分号 ; ：
```ini
;www.google.com = direct
```

**Comment by distance00** [comment]
请教一下，为什么xx-net没事儿，xx-mini不是和xx-net一样的核心吗？goproxy开了http2也没事。

**Comment by xyuanmu** [comment]
xx-net旧版本用直连也不行，代码更新后可以直连，现在没有时间更新代码，所以暂时先取消直连。

**Comment by xyuanmu** [comment]
今天抽空检查了下代码，知道原因了，其实并不是新代码支持直连，而是ip不支持下载，必须用gae模式，而gae模式连谷歌经常会出现验证码，新的xx-net代码直接将“appengine.google.com”以及“www.google.com”列入[白名单不使用直连](https://github.com/XX-net/XX-Net/commit/d89e35be6db878ec82281593276354c6fe37a4c1#diff-3)，暂时的思路是默认直连，不成功则切换成gae模式，很快会更新代码的。

**Comment by jzp820927** [comment]
Y 大回归，欣喜万分！
